server:
  port: 5000

spring:
  sleuth:
    sampler:
      # 采样请求的概率, 即以100% 的概率将链路的数据上传给 Zipkin Server
      probability: 1.0
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
      - id: user-api
        uri: lb://user-service
        predicates:
        - Path=/user-api/**
        filters:
        - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
