server:
  port: 8762

spring:
  sleuth:
    sampler:
      # 采样请求的概率, 即以100% 的概率将链路的数据上传给 Zipkin Server
      probability: 1.0
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

