server:
  port: 8769

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        git:
          uri: https://gitee.com/Joden_He/spring-cloud-config
          search-paths: respo
          username: xxx
          password: xxx
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/